remote_theme: jekyll/minima@3cdd14d
# theme: minima uses an older stable version, use remore_theme for minima theme
title: CogStat documentation

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed

minima:
  skin: classic
